/*
	Mount Sinai
	Authors: ChimpanG, Deliverator
*/

-----------------------------------------------
-- Effects for Natural Wonders
-- Effect: Holy Sites provide +1 Great Person Points toward Great Prophets for the player that owns this tile. Religious units may be purchased for half the amount of Faith.
-----------------------------------------------

	UPDATE	Features
	SET		Description = 'LOC_TM_FEATURE_SINAI_EFFECT_DESCRIPTION'
	WHERE	FeatureType = 'FEATURE_SINAI'
	AND EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_PROPHET'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_MISSIONARY'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_APOSTLE'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_INQUISITOR'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_GURU'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_WARRIOR_MONK'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

-----------------------------------------------
-- Modifiers
-----------------------------------------------

INSERT INTO Modifiers
		(ModifierId,												ModifierType,											OwnerRequirementSetId,				SubjectRequirementSetId					)
VALUES	('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_PROPHET',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',					'REQSET_TM_MAP_HAS_FEATURE_SINAI',	'REQSET_TM_PLAYER_HAS_FEATURE_SINAI'	),
		('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_MISSIONARY',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',					'REQSET_TM_MAP_HAS_FEATURE_SINAI',	'REQSET_TM_PLAYER_HAS_FEATURE_SINAI'	),
		('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_APOSTLE',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',					'REQSET_TM_MAP_HAS_FEATURE_SINAI',	'REQSET_TM_PLAYER_HAS_FEATURE_SINAI'	),
		('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_INQUISITOR',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',					'REQSET_TM_MAP_HAS_FEATURE_SINAI',	'REQSET_TM_PLAYER_HAS_FEATURE_SINAI'	),
		('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_GURU',			'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',					'REQSET_TM_MAP_HAS_FEATURE_SINAI',	'REQSET_TM_PLAYER_HAS_FEATURE_SINAI'	),
		('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_WARRIOR_MONK',	'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',					'REQSET_TM_MAP_HAS_FEATURE_SINAI',	'REQSET_TM_PLAYER_HAS_FEATURE_SINAI'	),
		('MODIFIER_TM_FEATURE_SINAI_HOLY_SITE_GP',					'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS',	NULL,								'DISTRICT_IS_HOLY_SITE'					),
		('MODIFIER_TM_FEATURE_SINAI_MISSIONARY_DISCOUNT',			'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST',		NULL,								NULL									),
		('MODIFIER_TM_FEATURE_SINAI_APOSTLE_DISCOUNT',				'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST',		NULL,								NULL									),
		('MODIFIER_TM_FEATURE_SINAI_INQUISITOR_DISCOUNT',			'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST',		NULL,								NULL									),
		('MODIFIER_TM_FEATURE_SINAI_GURU_DISCOUNT',					'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST',		NULL,								NULL									),
		('MODIFIER_TM_FEATURE_SINAI_WARRIOR_MONK_DISCOUNT',			'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST',		NULL,								NULL									);

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------

INSERT INTO ModifierArguments
		(ModifierId,												Name,					Value												)
VALUES	('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_PROPHET',		'ModifierId',			'MODIFIER_TM_FEATURE_SINAI_HOLY_SITE_GP'			),
		('MODIFIER_TM_FEATURE_SINAI_HOLY_SITE_GP',					'GreatPersonClassType',	'GREAT_PERSON_CLASS_PROPHET'						),
		('MODIFIER_TM_FEATURE_SINAI_HOLY_SITE_GP',					'Amount',				1													),
		('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_MISSIONARY',		'ModifierId',			'MODIFIER_TM_FEATURE_SINAI_MISSIONARY_DISCOUNT'		),
		('MODIFIER_TM_FEATURE_SINAI_MISSIONARY_DISCOUNT',			'UnitType',				'UNIT_MISSIONARY'									),
		('MODIFIER_TM_FEATURE_SINAI_MISSIONARY_DISCOUNT',			'Amount',				20													),
		('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_APOSTLE',		'ModifierId',			'MODIFIER_TM_FEATURE_SINAI_APOSTLE_DISCOUNT'		),
		('MODIFIER_TM_FEATURE_SINAI_APOSTLE_DISCOUNT',				'UnitType',				'UNIT_APOSTLE'										),
		('MODIFIER_TM_FEATURE_SINAI_APOSTLE_DISCOUNT',				'Amount',				20													),
		('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_INQUISITOR',		'ModifierId',			'MODIFIER_TM_FEATURE_SINAI_INQUISITOR_DISCOUNT'		),
		('MODIFIER_TM_FEATURE_SINAI_INQUISITOR_DISCOUNT',			'UnitType',				'UNIT_INQUISITOR'									),
		('MODIFIER_TM_FEATURE_SINAI_INQUISITOR_DISCOUNT',			'Amount',				20													),
		('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_GURU',			'ModifierId',			'MODIFIER_TM_FEATURE_SINAI_GURU_DISCOUNT'			),
		('MODIFIER_TM_FEATURE_SINAI_GURU_DISCOUNT',					'UnitType',				'UNIT_GURU'											),
		('MODIFIER_TM_FEATURE_SINAI_GURU_DISCOUNT',					'Amount',				20													),
		('MODIFIER_TM_FEATURE_SINAI_ATTACH_PLAYERS_WARRIOR_MONK',	'ModifierId',			'MODIFIER_TM_FEATURE_SINAI_WARRIOR_MONK_DISCOUNT'	),
		('MODIFIER_TM_FEATURE_SINAI_WARRIOR_MONK_DISCOUNT',			'UnitType',				'UNIT_WARRIOR_MONK'									),
		('MODIFIER_TM_FEATURE_SINAI_WARRIOR_MONK_DISCOUNT',			'Amount',				20													);