/*
	Validation
	Authors: ChimpanG, Deliverator
*/

-----------------------------------------------
-- ModValidation

-- This will determine what is active for the player
-----------------------------------------------

INSERT INTO ModValidation (Version)
VALUES	('BASE'				),
		('TERRA_MIRABILIS'	);

INSERT INTO ModValidation (Version)
SELECT	'DLC1'
WHERE EXISTS (SELECT Type FROM Types WHERE Type IN
(
'CIVILIZATION_POLAND',
'LEADER_JADWIGA'
));

INSERT INTO ModValidation (Version)
SELECT	'DLC2'
WHERE EXISTS (SELECT Type FROM Types WHERE Type IN
(
'CIVILIZATION_AUCKLAND',
'CIVILIZATION_ANTANANARIVO',
'CIVILIZATION_ARMAGH',
'CIVILIZATION_GRANADA',
'CIVILIZATION_MUSCAT',
'CIVILIZATION_PALENQUE',
'IMPROVEMENT_ALCAZAR',
'IMPROVEMENT_MONASTERY',
'FEATURE_EYJAFJALLAJOKULL',
'FEATURE_LYSEFJORDEN',
'FEATURE_GIANTS_CAUSEWAY'
));

INSERT INTO ModValidation (Version)
SELECT	'DLC3'
WHERE EXISTS (SELECT Type FROM Types WHERE Type IN
(
'CIVILIZATION_AUSTRALIA',
'LEADER_JOHN_CURTIN'
));

INSERT INTO ModValidation (Version)
SELECT	'DLC4'
WHERE EXISTS (SELECT Type FROM Types WHERE Type IN
(
'CIVILIZATION_MACEDON',
'CIVILIZATION_PERSIA',
'LEADER_ALEXANDER',
'LEADER_CYRUS'
));

INSERT INTO ModValidation (Version)
SELECT	'DLC5'
WHERE EXISTS (SELECT Type FROM Types WHERE Type IN
(
'CIVILIZATION_NUBIA',
'LEADER_AMANITORE'
));

INSERT INTO ModValidation (Version)
SELECT	'DLC6'
WHERE EXISTS (SELECT Type FROM Types WHERE Type IN
(
'CIVILIZATION_INDONESIA',
'CIVILIZATION_KHMER',
'LEADER_GITARJA',
'LEADER_JAYAVARMAN'
));

INSERT INTO ModValidation (Version)
SELECT	'XP1'
WHERE EXISTS (SELECT Type FROM Types WHERE Type IN
(
'CIVILIZATION_CREE',
'CIVILIZATION_GEORGIA',
'CIVILIZATION_KOREA',
'CIVILIZATION_MAPUCHE',
'CIVILIZATION_MONGOLIA',
'CIVILIZATION_NETHERLANDS',
'CIVILIZATION_SCOTLAND',
'CIVILIZATION_ZULU',
'LEADER_POUNDMAKER',
'LEADER_TAMAR',
'LEADER_SEONDEOK',
'LEADER_LAUTARO',
'LEADER_GENGHIS_KHAN',
'LEADER_WILHEMINA',
'LEADER_ROBERT_THE_BRUCE',
'LEADER_SHAKA',
'LEADER_CHANDRAGUPTA'
));

INSERT INTO ModValidation (Version)
SELECT	'XP2'
WHERE EXISTS (SELECT Type FROM Types WHERE Type IN
(
'CIVILIZATION_CANADA',
'CIVILIZATION_INCA',
'CIVILIZATION_HUNGARY',
'CIVILIZATION_MALI',
'CIVILIZATION_MAORI',
'CIVILIZATION_OTTOMAN',
'CIVILIZATION_SWEDEN',
'LEADER_LAURIER',
'LEADER_PACHACUTI',
'LEADER_MATTHIAS',
'LEADER_MANSA_MUSA',
'LEADER_KUPE',
'LEADER_SULEIMAN',
'LEADER_KRISTINA',
'LEADER_ELEANOR'
));


INSERT INTO ModValidation (Version)
SELECT	'DLC7'
WHERE EXISTS (SELECT Type FROM Types WHERE Type IN
(
'CIVILIZATION_MAYA',
'CIVILIZATION_GRAN_COLOMBIA',
'LEADER_LADY_SIX_SKY',
'LEADER_SIMON_BOLIVAR'
));