/*
	Ounianga
	Credits: ChimpanG, Deliverator
*/

-----------------------------------------------
-- Effects for Natural Wonders
-- Effect: Oases provide major adjacency bonuses to Specialty Districts for any Civilization that owns at least one of these tiles.
-----------------------------------------------

	UPDATE	Features
	SET		Description = 'LOC_TM_FEATURE_OUNIANGA_EFFECT_DESCRIPTION'
	WHERE	FeatureType = 'FEATURE_OUNIANGA'
	AND EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_HOLY_SITE'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_CAMPUS'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_THEATER'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_COMMERCIAL_HUB'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_INDUSTRIAL_ZONE'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_HARBOR'
	WHERE EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

-----------------------------------------------
-- Modifiers
-----------------------------------------------

INSERT INTO Modifiers
		(ModifierId,											ModifierType,						SubjectRequirementSetId					)
VALUES	('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_HOLY_SITE',		'MODTYPE_TM_ATTACH_ALL_PLAYERS',	'REQSET_TM_PLAYER_HAS_FEATURE_OUNIANGA'	),
		('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_CAMPUS',			'MODTYPE_TM_ATTACH_ALL_PLAYERS',	'REQSET_TM_PLAYER_HAS_FEATURE_OUNIANGA'	),
		('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_THEATER',			'MODTYPE_TM_ATTACH_ALL_PLAYERS',	'REQSET_TM_PLAYER_HAS_FEATURE_OUNIANGA'	),
		('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_COMMERCIAL_HUB',	'MODTYPE_TM_ATTACH_ALL_PLAYERS',	'REQSET_TM_PLAYER_HAS_FEATURE_OUNIANGA'	),
		('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_INDUSTRIAL_ZONE',	'MODTYPE_TM_ATTACH_ALL_PLAYERS',	'REQSET_TM_PLAYER_HAS_FEATURE_OUNIANGA'	),
		('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_HARBOR',			'MODTYPE_TM_ATTACH_ALL_PLAYERS',	'REQSET_TM_PLAYER_HAS_FEATURE_OUNIANGA'	),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HOLY_SITE',		'MODTYPE_TM_FEATURE_ADJACENCY',		NULL									),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_CAMPUS',			'MODTYPE_TM_FEATURE_ADJACENCY',		NULL									),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_THEATER',			'MODTYPE_TM_FEATURE_ADJACENCY',		NULL									),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_COMMERCIAL_HUB',	'MODTYPE_TM_FEATURE_ADJACENCY',		NULL									),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_INDUSTRIAL_ZONE',	'MODTYPE_TM_FEATURE_ADJACENCY',		NULL									),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HARBOR',			'MODTYPE_TM_FEATURE_ADJACENCY',		NULL									);

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------

INSERT INTO ModifierArguments
		(ModifierId,											Name,				Value													)
VALUES	('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_HOLY_SITE',		'ModifierId',		'MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HOLY_SITE'			),
		('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_CAMPUS',			'ModifierId',		'MODIFIER_TM_FEATURE_OUNIANGA_OASIS_CAMPUS'				),
		('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_THEATER',			'ModifierId',		'MODIFIER_TM_FEATURE_OUNIANGA_OASIS_THEATER'			),
		('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_COMMERCIAL_HUB',	'ModifierId',		'MODIFIER_TM_FEATURE_OUNIANGA_OASIS_COMMERCIAL_HUB'		),
		('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_INDUSTRIAL_ZONE',	'ModifierId',		'MODIFIER_TM_FEATURE_OUNIANGA_OASIS_INDUSTRIAL_ZONE'	),
		('MODIFIER_TM_FEATURE_OUNIANGA_ATTACH_HARBOR',			'ModifierId',		'MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HARBOR'				),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HOLY_SITE',		'DistrictType',		'DISTRICT_HOLY_SITE'									),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HOLY_SITE',		'FeatureType',		'FEATURE_OASIS'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HOLY_SITE',		'YieldType',		'YIELD_FAITH'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HOLY_SITE',		'Amount',			2														),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HOLY_SITE',		'Description',		'LOC_ADJ_OUNIANGA_FAITH_DESCRIPTION'					),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_CAMPUS',			'DistrictType',		'DISTRICT_CAMPUS'										),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_CAMPUS',			'FeatureType',		'FEATURE_OASIS'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_CAMPUS',			'YieldType',		'YIELD_SCIENCE'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_CAMPUS',			'Amount',			2														),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_CAMPUS',			'Description',		'LOC_ADJ_OUNIANGA_SCIENCE_DESCRIPTION'					),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_THEATER',			'DistrictType',		'DISTRICT_THEATER'										),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_THEATER',			'FeatureType',		'FEATURE_OASIS'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_THEATER',			'YieldType',		'YIELD_CULTURE'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_THEATER',			'Amount',			2														),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_THEATER',			'Description',		'LOC_ADJ_OUNIANGA_CULTURE_DESCRIPTION'					),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_COMMERCIAL_HUB',	'DistrictType',		'DISTRICT_COMMERCIAL_HUB'								),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_COMMERCIAL_HUB',	'FeatureType',		'FEATURE_OASIS'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_COMMERCIAL_HUB',	'YieldType',		'YIELD_GOLD'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_COMMERCIAL_HUB',	'Amount',			2														),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_COMMERCIAL_HUB',	'Description',		'LOC_ADJ_OUNIANGA_GOLD_DESCRIPTION'						),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_INDUSTRIAL_ZONE',	'DistrictType',		'DISTRICT_INDUSTRIAL_ZONE'								),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_INDUSTRIAL_ZONE',	'FeatureType',		'FEATURE_OASIS'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_INDUSTRIAL_ZONE',	'YieldType',		'YIELD_PRODUCTION'										),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_INDUSTRIAL_ZONE',	'Amount',			2														),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_INDUSTRIAL_ZONE',	'Description',		'LOC_ADJ_OUNIANGA_PRODUCTION_DESCRIPTION'				),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HARBOR',			'DistrictType',		'DISTRICT_HARBOR'										),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HARBOR',			'FeatureType',		'FEATURE_OASIS'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HARBOR',			'YieldType',		'YIELD_GOLD'											),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HARBOR',			'Amount',			2														),
		('MODIFIER_TM_FEATURE_OUNIANGA_OASIS_HARBOR',			'Description',		'LOC_ADJ_OUNIANGA_GOLD_DESCRIPTION'						);
